name: Python Report Pusher

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * *'
    - cron: '0 16 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create Report
      run: |
        python main.py
